import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

class SampleDataHelper {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static Future<void> addSampleRecipes() async {
    List<Map<String, dynamic>> sampleRecipes = [
      //breakfast
      {
        'title': 'Fluffy Blueberry Pancakes',
        'description': 'Golden pancakes packed with fresh blueberries and served with maple syrup. These pancakes are incredibly soft and airy, making them a perfect comfort food for a slow weekend morning.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2017/05/07/08/56/pancakes-2291908_1280.jpg',
        'cookTime': 25,
        'calories': 350,
        'rating': 4.8,
        'category': 'Breakfast',
        'ingredients': ['2 cups flour', '2 eggs', '1.5 cups milk', '1 cup blueberries', '2 tbsp sugar', 'Butter'],
        'steps': ['Mix dry ingredients', 'Whisk wet ingredients', 'Combine gently', 'Fold in blueberries', 'Cook on griddle until golden'],
        'authorId': 'chef_team',
        'authorName': 'RecipeGO Chef',
        'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
      },
      {
        'title': 'Avocado Toast Deluxe',
        'description': 'Crispy sourdough topped with creamy avocado, poached egg, and chili flakes. A nutrient-dense meal that provides healthy fats and protein to keep you energized throughout the day.',
        'imageUrl': 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800',
        'cookTime': 15,
        'calories': 280,
        'rating': 4.6,
        'category': 'Breakfast',
        'ingredients': ['2 slices sourdough bread', '1 ripe avocado', '2 eggs', 'Chili flakes', 'Lemon juice', 'Salt & pepper'],
        'steps': ['Toast the bread', 'Mash avocado with lemon and salt', 'Poach the eggs', 'Assemble and sprinkle with chili flakes'],
        'authorId': 'chef_team',
        'authorName': 'Healthy Eats',
        'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
      },
      {
        'title': 'Classic French Omelette',
        'description': 'Buttery, soft herbs omelette cooked to perfection. This elegant dish requires a bit of technique but rewards you with a silky texture and delicate flavor that is truly classic.',
        'imageUrl': 'https://images.unsplash.com/photo-1587486913049-53fc88980cfc?w=800',
        'cookTime': 10,
        'calories': 220,
        'rating': 4.5,
        'category': 'Breakfast',
        'ingredients': ['3 eggs', '1 tbsp butter', 'Chives', 'Parsley', 'Salt', 'Black pepper'],
        'steps': ['Whisk eggs vigorously', 'Melt butter in pan', 'Pour eggs and shake pan', 'Fold and serve soft'],
        'authorId': 'chef_team',
        'authorName': 'Chef Pierre',
        'createdAt': DateTime.now().subtract(const Duration(days: 3)).toIso8601String(),
      },
      {
        'title': 'Tropical Smoothie Bowl',
        'description': 'A refreshing blend of mango, pineapple, and banana topped with granola. A vibrant and healthy way to start your day, packed with vitamins and natural sweetness from fresh fruits.',
        'imageUrl': 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=800',
        'cookTime': 10,
        'calories': 310,
        'rating': 4.7,
        'category': 'Breakfast',
        'ingredients': ['1 frozen banana', '1 cup mango chunks', '1/2 cup coconut milk', 'Granola', 'Chia seeds'],
        'steps': ['Blend fruits and milk until thick', 'Pour into bowl', 'Top with granola and seeds', 'Serve immediately'],
        'authorId': 'chef_team',
        'authorName': 'Smoothie King',
        'createdAt': DateTime.now().subtract(const Duration(days: 4)).toIso8601String(),
      },
      {
        'title': 'Hearty Breakfast Burrito',
        'description': 'Scrambled eggs, black beans, cheese, and salsa wrapped in a warm tortilla. This filling breakfast option is perfect for those on the go, providing a balanced mix of protein, fiber, and delicious Tex-Mex flavors.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2017/06/29/20/09/mexican-2456038_1280.jpg',
        'cookTime': 15,
        'calories': 520,
        'rating': 4.7,
        'category': 'Breakfast',
        'ingredients': ['2 tortillas', '4 eggs', '1/2 cup black beans', '1/2 cup cheese', 'Salsa', 'Avocado'],
        'steps': ['Scramble the eggs', 'Warm the tortillas', 'Layer beans, eggs, and cheese', 'Roll tightly and serve with salsa'],
        'authorId': 'chef_team',
        'authorName': 'Breakfast Pro',
        'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
      },
      {
        'title': 'Classic Belgian Waffles',
        'description': 'Golden crispy waffles topped with fresh strawberries and whipped cream. Indulge in these light and fluffy waffles that feature deep pockets for catching plenty of syrup and fresh fruit juice.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2012/03/02/10/52/belgian-21017_1280.jpg',
        'cookTime': 20,
        'calories': 450,
        'rating': 4.8,
        'category': 'Breakfast',
        'ingredients': ['2 cups waffle mix', '1.5 cups water', 'Strawberries', 'Whipped cream', 'Maple syrup'],
        'steps': ['Preheat waffle iron', 'Mix batter until smooth', 'Cook until golden brown', 'Top with fruit and cream'],
        'authorId': 'chef_team',
        'authorName': 'Waffle House',
        'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
      },
      {
        'title': 'Overnight Berry Oats',
        'description': 'Creamy oats soaked overnight with chia seeds and mixed berries. A hassle-free breakfast that prepares itself while you sleep, offering a cool and refreshing start to your morning with zero cooking required.',
        'imageUrl': 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?w=800',
        'cookTime': 5,
        'calories': 290,
        'rating': 4.5,
        'category': 'Breakfast',
        'ingredients': ['1 cup oats', '1 cup almond milk', '1/2 cup berries', '1 tbsp chia seeds', 'Honey'],
        'steps': ['Combine oats, milk, and chia seeds', 'Stir in honey', 'Refrigerate overnight', 'Top with fresh berries'],
        'authorId': 'chef_team',
        'authorName': 'Healthy Eats',
        'createdAt': DateTime.now().subtract(const Duration(days: 3)).toIso8601String(),
      },
      {
        'title': 'Spicy Shakshuka',
        'description': 'Poached eggs in a simmering tomato and pepper sauce with feta cheese. A bold and spicy North African breakfast that is rich in flavor and perfect for sharing, especially when served with crusty bread.',
        'imageUrl': 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800',
        'cookTime': 30,
        'calories': 340,
        'rating': 4.6,
        'category': 'Breakfast',
        'ingredients': ['4 eggs', '1 can crushed tomatoes', '1 bell pepper', 'Onion', 'Garlic', 'Feta cheese', 'Cumin'],
        'steps': ['Sauté onion and peppers', 'Add tomatoes and spices', 'Simmer until thickened', 'Crack eggs into sauce', 'Cook until whites are set'],
        'authorId': 'chef_team',
        'authorName': 'Chef Omar',
        'createdAt': DateTime.now().subtract(const Duration(days: 4)).toIso8601String(),
      },

      // lunch
      {
        'title': 'Grilled Chicken Caesar',
        'description': 'Crisp romaine lettuce with grilled chicken, parmesan, and homemade croutons. This classic salad is elevated with a savory grilled chicken breast and a rich, creamy dressing that everyone loves.',
        'imageUrl': 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800',
        'cookTime': 20,
        'calories': 420,
        'rating': 4.4,
        'category': 'Lunch',
        'ingredients': ['Chicken breast', 'Romaine lettuce', 'Parmesan cheese', 'Croutons', 'Caesar dressing'],
        'steps': ['Grill seasoned chicken', 'Chop lettuce', 'Toss with dressing', 'Top with sliced chicken and cheese'],
        'authorId': 'chef_team',
        'authorName': 'Salad Master',
        'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
      },
      {
        'title': 'Spicy Tuna Roll Bowl',
        'description': 'Deconstructed sushi roll with rice, tuna, cucumber, and spicy mayo. All the flavors of your favorite sushi roll in a convenient bowl format that is healthy and easy to prepare.',
        'imageUrl': 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800',
        'cookTime': 15,
        'calories': 380,
        'rating': 4.9,
        'category': 'Lunch',
        'ingredients': ['Sushi rice', 'Fresh tuna (sashimi grade)', 'Cucumber', 'Avocado', 'Spicy mayo', 'Nori strips'],
        'steps': ['Cook rice', 'Dice tuna and veggies', 'Mix tuna with spicy mayo', 'Assemble bowl with rice base'],
        'authorId': 'chef_team',
        'authorName': 'Sushi Chef',
        'createdAt': DateTime.now().subtract(const Duration(days: 5)).toIso8601String(),
      },
      {
        'title': 'Margherita Pizza',
        'description': 'Classic Neapolitan pizza with fresh basil, mozzarella, and tomato sauce. Simple yet incredibly satisfying, this pizza relies on the quality of its fresh ingredients and a high-heat bake for the perfect crust.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2017/12/09/08/18/pizza-3007395_1280.jpg',
        'cookTime': 25,
        'calories': 850,
        'rating': 4.8,
        'category': 'Lunch',
        'ingredients': ['Pizza dough', 'San Marzano tomato sauce', 'Fresh Mozzarella', 'Basil leaves', 'Olive oil'],
        'steps': ['Stretch dough', 'Spread sauce', 'Add cheese', 'Bake at max temp for 10 mins', 'Top with basil'],
        'authorId': 'chef_team',
        'authorName': 'Pizza Lover',
        'createdAt': DateTime.now().subtract(const Duration(days: 6)).toIso8601String(),
      },
      {
        'title': 'Veggie Quinoa Bowl',
        'description': 'Nutrient-packed bowl with roasted veggies and tahini dressing. A power lunch that combines complex carbohydrates, plant-based protein, and plenty of fiber to keep you full and focused.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2017/10/09/19/29/eat-2834549_1280.jpg',
        'cookTime': 35,
        'calories': 450,
        'rating': 4.3,
        'category': 'Lunch',
        'ingredients': ['Quinoa', 'Sweet potato', 'Chickpeas', 'Kale', 'Tahini', 'Lemon'],
        'steps': ['Cook quinoa', 'Roast sweet potato and chickpeas', 'Massage kale', 'Whisk dressing', 'Combine all'],
        'authorId': 'chef_team',
        'authorName': 'Green Life',
        'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
      },
      {
        'title': 'Caprese Panini',
        'description': 'Fresh mozzarella, tomatoes, and pesto pressed between ciabatta bread. A simple yet elegant lunch that captures the essence of Italian cuisine with melting cheese and fragrant basil pesto.',
        'imageUrl': 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800',
        'cookTime': 10,
        'calories': 480,
        'rating': 4.6,
        'category': 'Lunch',
        'ingredients': ['Ciabatta bread', 'Fresh mozzarella', 'Tomato slices', 'Pesto sauce', 'Balsamic glaze'],
        'steps': ['Spread pesto on bread', 'Layer cheese and tomatoes', 'Press in panini maker', 'Drizzle with balsamic'],
        'authorId': 'chef_team',
        'authorName': 'Sandwich Shop',
        'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
      },
      {
        'title': 'Greek Salad Bowl',
        'description': 'Crisp cucumbers, olives, feta, and tomatoes with a lemon-herb dressing. A light and healthy Mediterranean classic that is bursting with freshness and tangy flavors from the feta and olives.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2017/09/16/19/21/salad-2756467_1280.jpg',
        'cookTime': 15,
        'calories': 310,
        'rating': 4.4,
        'category': 'Lunch',
        'ingredients': ['Cucumber', 'Cherry tomatoes', 'Kalamata olives', 'Red onion', 'Feta cheese', 'Lemon dressing'],
        'steps': ['Chop all vegetables', 'Combine in a large bowl', 'Toss with dressing', 'Top with crumbled feta'],
        'authorId': 'chef_team',
        'authorName': 'Salad Master',
        'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
      },
      {
        'title': 'Chicken Banh Mi',
        'description': 'Vietnamese sandwich with grilled chicken, pickled veggies, and cilantro. Experience an explosion of textures and flavors in this traditional sandwich, featuring a crispy baguette and savory grilled protein.',
        'imageUrl': 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=800',
        'cookTime': 20,
        'calories': 560,
        'rating': 4.8,
        'category': 'Lunch',
        'ingredients': ['Baguette', 'Grilled chicken', 'Pickled carrots', 'Daikon', 'Cilantro', 'Sriracha mayo'],
        'steps': ['Slice baguette longways', 'Spread mayo', 'Add grilled chicken', 'Top with pickled veggies and cilantro'],
        'authorId': 'chef_team',
        'authorName': 'Asian Fusion',
        'createdAt': DateTime.now().subtract(const Duration(days: 3)).toIso8601String(),
      },
      {
        'title': 'Lentil Vegetable Soup',
        'description': 'Hearty and warming soup packed with lentils and seasonal vegetables. A nutritious and comforting lunch option that is low in fat but high in protein and essential minerals to keep you satiated.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2017/06/16/11/38/soup-2408818_1280.jpg',
        'cookTime': 40,
        'calories': 380,
        'rating': 4.5,
        'category': 'Lunch',
        'ingredients': ['1 cup dry lentils', '2 carrots', '2 stalks celery', '1 onion', 'Vegetable broth', 'Spinach'],
        'steps': ['Sauté aromatics', 'Add lentils and broth', 'Simmer for 30 mins', 'Stir in spinach at the end'],
        'authorId': 'chef_team',
        'authorName': 'Green Life',
        'createdAt': DateTime.now().subtract(const Duration(days: 4)).toIso8601String(),
      },

      // dinner
      {
        'title': 'Juicy Beef Burger',
        'description': 'Perfectly grilled beef patty with melted cheese and fresh toppings. This burger is the ultimate dinner treat, featuring a juicy handmade patty and artisanal toppings that take classic comfort food to the next level.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2016/03/05/19/02/hamburger-1238246_1280.jpg',
        'cookTime': 30,
        'calories': 720,
        'rating': 4.9,
        'category': 'Dinner',
        'ingredients': ['Beef patty', 'Brioche bun', 'Cheddar cheese', 'Lettuce', 'Tomato', 'Special sauce'],
        'steps': ['Grill patty 4 mins per side', 'Toast buns', 'Melt cheese on patty', 'Assemble burger'],
        'authorId': 'chef_team',
        'authorName': 'Grill Master',
        'createdAt': DateTime.now().subtract(const Duration(days: 7)).toIso8601String(),
      },
      {
        'title': 'Creamy Mushroom Pasta',
        'description': 'Tagliatelle pasta tossed in a rich garlic parmesan mushroom sauce. A sophisticated yet simple meal that brings earthy flavors and creamy indulgence together for a restaurant-quality dinner at home.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2018/07/18/19/12/pasta-3547078_1280.jpg',
        'cookTime': 25,
        'calories': 580,
        'rating': 4.6,
        'category': 'Dinner',
        'ingredients': ['Tagliatelle pasta', 'Mixed mushrooms', 'Heavy cream', 'Garlic', 'Parmesan', 'Thyme'],
        'steps': ['Cook pasta', 'Sauté mushrooms and garlic', 'Add cream and simmer', 'Toss pasta in sauce'],
        'authorId': 'chef_team',
        'authorName': 'Pasta Chef',
        'createdAt': DateTime.now().subtract(const Duration(days: 3)).toIso8601String(),
      },
      {
        'title': 'Pan-Seared Salmon',
        'description': 'Crispy skin salmon fillet with lemon butter asparagus. This healthy and delicious dinner is packed with omega-3s and features a perfectly seared crust that contrasts beautifully with the tender, flaky fish inside.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2014/11/05/15/57/salmon-518032_1280.jpg',
        'cookTime': 20,
        'calories': 410,
        'rating': 4.8,
        'category': 'Dinner',
        'ingredients': ['Salmon fillet', 'Asparagus', 'Lemon', 'Butter', 'Garlic', 'Dill'],
        'steps': ['Season salmon', 'Sear skin-side down for 5 mins', 'Flip and baste with butter', 'Sauté asparagus'],
        'authorId': 'chef_team',
        'authorName': 'Seafood Pro',
        'createdAt': DateTime.now().subtract(const Duration(days: 4)).toIso8601String(),
      },
      {
        'title': 'Vegetable Stir-Fry',
        'description': 'Colorful mix of fresh veggies in a savory soy-ginger sauce. A quick and easy dinner that is both nutritious and flavorful, perfect for utilizing any fresh seasonal vegetables you have on hand.',
        'imageUrl': 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
        'cookTime': 20,
        'calories': 320,
        'rating': 4.2,
        'category': 'Dinner',
        'ingredients': ['Broccoli', 'Bell peppers', 'Carrots', 'Tofu or Chicken', 'Soy sauce', 'Ginger', 'Garlic'],
        'steps': ['Slice veggies', 'Stir-fry protein', 'Add veggies and sauce', 'Serve over rice'],
        'authorId': 'chef_team',
        'authorName': 'Wok Star',
        'createdAt': DateTime.now().subtract(const Duration(days: 5)).toIso8601String(),
      },
      {
        'title': 'Street Style Tacos',
        'description': 'Three soft corn tortillas with seasoned beef, onions, and fresh cilantro. Bring the vibrant taste of a Mexican street food market to your dinner table with these quick, flavorful, and incredibly easy-to-assemble tacos.',
        'imageUrl': 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800',
        'cookTime': 25,
        'calories': 480,
        'rating': 4.9,
        'category': 'Dinner',
        'ingredients': ['Ground beef', 'Corn tortillas', 'Onion', 'Cilantro', 'Lime', 'Taco seasoning'],
        'steps': ['Brown beef with seasoning', 'Warm tortillas in a pan', 'Fill with beef, onions, and cilantro', 'Serve with lime wedges'],
        'authorId': 'chef_team',
        'authorName': 'Taco Star',
        'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
      },
      {
        'title': 'Garlic Shrimp Scampi',
        'description': 'Succulent shrimp sautéed in a garlic butter and lemon sauce over pasta. A luxurious and fast dinner that feels special enough for any occasion, featuring tender shrimp and a zesty, aromatic sauce.',
        'imageUrl': 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800',
        'cookTime': 20,
        'calories': 520,
        'rating': 4.7,
        'category': 'Dinner',
        'ingredients': ['Large shrimp', 'Linguine pasta', 'Garlic', 'Butter', 'Lemon juice', 'Parsley'],
        'steps': ['Cook pasta', 'Sauté shrimp with garlic and butter', 'Stir in lemon juice and parsley', 'Toss with pasta'],
        'authorId': 'chef_team',
        'authorName': 'Seafood Pro',
        'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
      },
      {
        'title': 'Baked Eggplant Parmesan',
        'description': 'Crispy eggplant slices layered with marinara and melted mozzarella. A lighter, baked version of the Italian classic that doesn\'t sacrifice any of the comforting, cheesy goodness you expect from eggplant parmesan.',
        'imageUrl': 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
        'cookTime': 45,
        'calories': 420,
        'rating': 4.4,
        'category': 'Dinner',
        'ingredients': ['Eggplant', 'Marinara sauce', 'Mozzarella cheese', 'Parmesan', 'Breadcrumbs', 'Egg'],
        'steps': ['Bread and bake eggplant slices', 'Layer with sauce and cheeses', 'Bake until bubbly', 'Serve hot'],
        'authorId': 'chef_team',
        'authorName': 'Pasta Chef',
        'createdAt': DateTime.now().subtract(const Duration(days: 4)).toIso8601String(),
      },

      // === DESSERT ===
      {
        'title': 'Molten Lava Cake',
        'description': 'Decadent chocolate cake with a gooey molten center. This dessert is a chocolate lover\'s dream, served warm with a surprising liquid center that pairs perfectly with a scoop of vanilla bean ice cream.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2016/11/22/18/52/cake-1850011_1280.jpg',
        'cookTime': 25,
        'calories': 480,
        'rating': 5.0,
        'category': 'Dessert',
        'ingredients': ['Dark chocolate', 'Butter', 'Eggs', 'Sugar', 'Flour', 'Vanilla'],
        'steps': ['Melt chocolate and butter', 'Whisk eggs and sugar', 'Combine and bake for 12 mins', 'Serve warm'],
        'authorId': 'chef_team',
        'authorName': 'Baker Jo',
        'createdAt': DateTime.now().subtract(const Duration(days: 8)).toIso8601String(),
      },
      {
        'title': 'Berry Cheesecake',
        'description': 'No-bake cheesecake topped with fresh mixed berries. A light and airy dessert that\'s strikingly beautiful and wonderfully refreshing, perfect for those who want a sweet treat without turning on the oven.',
        'imageUrl': 'https://images.unsplash.com/photo-156732737114-b5c9b9c4a3c7?w=800',
        'cookTime': 20,
        'calories': 420,
        'rating': 4.7,
        'category': 'Dessert',
        'ingredients': ['Digestive biscuits', 'Cream cheese', 'Heavy cream', 'Sugar', 'Berries'],
        'steps': ['Crush biscuits for base', 'Whip cheese and cream', 'Layer and chill', 'Top with berries'],
        'authorId': 'chef_team',
        'authorName': 'Sweet Tooth',
        'createdAt': DateTime.now().subtract(const Duration(days: 6)).toIso8601String(),
      },
      {
        'title': 'Soft Chocolate Chip Cookies',
        'description': 'Classic chewy cookies with melting chocolate chunks. The definitive chocolate chip cookie recipe that yields soft centers and slightly crisp edges, packed with premium chocolate for the perfect bite every time.',
        'imageUrl': 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800',
        'cookTime': 15,
        'calories': 210,
        'rating': 4.9,
        'category': 'Dessert',
        'ingredients': ['Flour', 'Butter', 'Sugar', 'Eggs', 'Chocolate chips', 'Vanilla'],
        'steps': ['Cream butter and sugar', 'Mix in eggs and dry ingredients', 'Fold in chips', 'Bake at 350F for 10 mins'],
        'authorId': 'chef_team',
        'authorName': 'Baker Jo',
        'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
      },
      {
        'title': 'Warm Apple Crumble',
        'description': 'Spiced apples topped with a buttery oat crumble and vanilla ice cream. A rustic and heartwarming dessert that brings together the sweetness of baked apples and the satisfying crunch of a toasted oat topping.',
        'imageUrl': 'https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=800',
        'cookTime': 40,
        'calories': 380,
        'rating': 4.7,
        'category': 'Dessert',
        'ingredients': ['Apples', 'Oats', 'Sugar', 'Cinnamon', 'Butter', 'Flour'],
        'steps': ['Slice and spice apples', 'Mix crumble ingredients', 'Top apples with crumble', 'Bake until golden'],
        'authorId': 'chef_team',
        'authorName': 'Sweet Tooth',
        'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
      },
      {
        'title': 'Lemon Drizzle Cake',
        'description': 'Zesty and moist sponge cake topped with a sweet lemon glaze. This cake is a burst of sunshine in every bite, featuring a fine crumb and a sharp, tangy syrup that keeps it incredibly moist for days.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2017/01/11/11/33/cake-1971552_1280.jpg',
        'cookTime': 50,
        'calories': 340,
        'rating': 4.6,
        'category': 'Dessert',
        'ingredients': ['Flour', 'Butter', 'Eggs', 'Lemons', 'Sugar', 'Baking powder'],
        'steps': ['Mix cake batter', 'Bake until done', 'Mix lemon juice and sugar for glaze', 'Pour over hot cake'],
        'authorId': 'chef_team',
        'authorName': 'Baker Jo',
        'createdAt': DateTime.now().subtract(const Duration(days: 3)).toIso8601String(),
      },
      {
        'title': 'Classic Tiramisu',
        'description': 'Italian coffee-flavored dessert with layers of mascarpone and ladyfingers. A sophisticated adult treat that balances the bitterness of strong espresso with the rich, velvety sweetness of mascarpone cream.',
        'imageUrl': 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800',
        'cookTime': 30,
        'calories': 450,
        'rating': 4.8,
        'category': 'Dessert',
        'ingredients': ['Mascarpone', 'Espresso', 'Ladyfingers', 'Cocoa powder', 'Sugar', 'Eggs'],
        'steps': ['Dip ladyfingers in coffee', 'Layer with mascarpone cream', 'Chill for 4 hours', 'Dust with cocoa'],
        'authorId': 'chef_team',
        'authorName': 'Chef Pierre',
        'createdAt': DateTime.now().subtract(const Duration(days: 4)).toIso8601String(),
      },
      {
        'title': 'Vanilla Panna Cotta',
        'description': 'Silky smooth cream dessert topped with raspberry coulis. This elegant Italian dessert is deceptively simple to make but produces a professional-level result with its wobbling texture and vibrant berry sauce.',
        'imageUrl': 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800',
        'cookTime': 20,
        'calories': 310,
        'rating': 4.5,
        'category': 'Dessert',
        'ingredients': ['Heavy cream', 'Sugar', 'Vanilla bean', 'Gelatin', 'Raspberries'],
        'steps': ['Heat cream and sugar', 'Dissolve gelatin', 'Pour into molds and chill', 'Top with berry sauce'],
        'authorId': 'chef_team',
        'authorName': 'Sweet Tooth',
        'createdAt': DateTime.now().subtract(const Duration(days: 5)).toIso8601String(),
      },
      {
        'title': 'Homemade Banana Bread',
        'description': 'Sweet and moist bread made with ripened bananas and walnuts. A timeless classic that uses up those overripe bananas for a moist, cake-like loaf that is perfect for breakfast or an afternoon snack with tea.',
        'imageUrl': 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=800',
        'cookTime': 60,
        'calories': 280,
        'rating': 4.7,
        'category': 'Dessert',
        'ingredients': ['3 ripe bananas', 'Flour', 'Butter', 'Sugar', 'Egg', 'Walnuts'],
        'steps': ['Mash bananas', 'Combine with wet ingredients', 'Stir in dry ingredients', 'Bake at 350F for 1 hour'],
        'authorId': 'chef_team',
        'authorName': 'Baker Jo',
        'createdAt': DateTime.now().subtract(const Duration(days: 6)).toIso8601String(),
      },
       
      // snacks
       {
        'title': 'Guacamole & Chips',
        'description': 'Fresh homemade guacamole with crispy tortilla chips. A perfect party snack or side dish that brings the authentic flavors of Mexico right to your table with creamy avocados and zest lime.',
        'imageUrl': 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800',
        'cookTime': 10,
        'calories': 450,
        'rating': 4.9,
        'category': 'Snacks',
        'ingredients': ['3 avocados', '1 lime', 'Cilantro', 'Red onion', 'Tortilla chips'],
        'steps': ['Mash avocados', 'Mix in onion, cilantro, lime', 'Season with salt', 'Serve with chips'],
        'authorId': 'chef_team',
        'authorName': 'Snack Attack',
        'createdAt': DateTime.now().subtract(const Duration(days: 7)).toIso8601String(),
      },
      {
        'title': 'Classic Hummus & Pita',
        'description': 'Smooth chickpea dip served with warm pita bread and olive oil. A staple of Middle Eastern cuisine, this hummus is creamy and flavorful, providing a satisfying and healthy snack that\'s perfect for dipping.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2016/09/06/14/24/hummus-1649230_1280.jpg',
        'cookTime': 10,
        'calories': 320,
        'rating': 4.6,
        'category': 'Snacks',
        'ingredients': ['Chickpeas', 'Tahini', 'Lemon juice', 'Garlic', 'Warm pita bread'],
        'steps': ['Blend chickpeas, tahini, lemon, and garlic', 'Drizzle with olive oil', 'Serve with warm pita slices'],
        'authorId': 'chef_team',
        'authorName': 'Green Life',
        'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
      },
      {
        'title': 'Roasted Chickpeas',
        'description': 'Crunchy and spiced chickpeas, the perfect healthy protein snack. High in fiber and protein, these roasted chickpeas are a great alternative to potato chips when you’re craving something salty and crunchy.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2016/07/11/08/24/chickpeas-1509089_1280.jpg',
        'cookTime': 30,
        'calories': 210,
        'rating': 4.4,
        'category': 'Snacks',
        'ingredients': ['1 can chickpeas', 'Olive oil', 'Cumin', 'Paprika', 'Salt'],
        'steps': ['Drain and dry chickpeas', 'Toss with oil and spices', 'Roast at 400F for 30 mins until crunchy'],
        'authorId': 'chef_team',
        'authorName': 'Healthy Eats',
        'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
      },
      {
        'title': 'Sweet & Salty Trail Mix',
        'description': 'A mix of nuts, dried fruits, and chocolate for an energy boost. Whether you\'re hiking or just need a mid-afternoon pick-me-up, this trail mix provides the perfect balance of savory and sweet flavors.',
        'imageUrl': 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800',
        'cookTime': 5,
        'calories': 350,
        'rating': 4.3,
        'category': 'Snacks',
        'ingredients': ['Almonds', 'Walnuts', 'Raisins', 'M&Ms', 'Pretzels'],
        'steps': ['Combine all ingredients in a bowl', 'Mix well', 'Store in an airtight container'],
        'authorId': 'chef_team',
        'authorName': 'Snack Attack',
        'createdAt': DateTime.now().subtract(const Duration(days: 3)).toIso8601String(),
      },
      {
        'title': 'Peanut Butter Energy Balls',
        'description': 'No-bake snacks made with oats, peanut butter, and honey. These bite-sized treats are packed with nutrition and natural sweetness, making them an ideal snack for children and adults alike.',
        'imageUrl': 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800',
        'cookTime': 15,
        'calories': 180,
        'rating': 4.7,
        'category': 'Snacks',
        'ingredients': ['1 cup oats', '1/2 cup peanut butter', '1/3 cup honey', 'Chocolate chips'],
        'steps': ['Mix all ingredients together', 'Roll into 1-inch balls', 'Refrigerate for 30 mins before serving'],
        'authorId': 'chef_team',
        'authorName': 'Healthy Eats',
        'createdAt': DateTime.now().subtract(const Duration(days: 4)).toIso8601String(),
      },
      {
        'title': 'Fresh Fruit Skewers',
        'description': 'Colorful seasonal fruits served on a stick with a honey yogurt dip. A fun and vibrant way to enjoy your daily serving of fruit, especially popular at summer gatherings and children’s parties.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2017/05/11/19/44/fresh-fruits-2305192_1280.jpg',
        'cookTime': 15,
        'calories': 150,
        'rating': 4.5,
        'category': 'Snacks',
        'ingredients': ['Strawberries', 'Pineapple', 'Grapes', 'Melon', 'Greek yogurt', 'Honey'],
        'steps': ['Cut fruit into chunks', 'Thread onto skewers', 'Mix yogurt and honey for dipping'],
        'authorId': 'chef_team',
        'authorName': 'Summer Vibes',
        'createdAt': DateTime.now().subtract(const Duration(days: 5)).toIso8601String(),
      },
      {
        'title': 'Cheese & Crackers Plate',
        'description': 'Selection of artisanal cheeses with crispy crackers and grapes. An elegant and simple snack plate that combines the richness of cheese with the sweetness of fresh grapes and the crunch of crackers.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2016/03/05/22/03/cheese-1238395_1280.jpg',
        'cookTime': 10,
        'calories': 420,
        'rating': 4.6,
        'category': 'Snacks',
        'ingredients': ['Cheddar cheese', 'Brie', 'Water crackers', 'Red grapes', 'Almonds'],
        'steps': ['Slice cheeses', 'Arrange on a plate with crackers and fruit', 'Garnish with nuts'],
        'authorId': 'chef_team',
        'authorName': 'Snack Attack',
        'createdAt': DateTime.now().subtract(const Duration(days: 6)).toIso8601String(),
      },
      {
        'title': 'Herb Seasoned Popcorn',
        'description': 'Light and airy popcorn tossed in olive oil and dried herbs. A guilt-free snack that\'s full of aromatic herbs and provides a satisfying crunch without the heavy calories of traditional buttered popcorn.',
        'imageUrl': 'https://cdn.pixabay.com/photo/2015/05/30/01/18/popcorn-789198_1280.jpg',
        'cookTime': 10,
        'calories': 120,
        'rating': 4.2,
        'category': 'Snacks',
        'ingredients': ['Popcorn kernels', 'Olive oil', 'Dried rosemary', 'Garlic powder', 'Salt'],
        'steps': ['Pop the corn kernels', 'Drizzle with olive oil', 'Toss with herbs and salt while warm'],
        'authorId': 'chef_team',
        'authorName': 'Snack Attack',
        'createdAt': DateTime.now().subtract(const Duration(days: 7)).toIso8601String(),
      },
      
      // drinks
      {
        'title': 'Iced Matcha Latte',
        'description': 'Refreshing iced green tea latte with oat milk. This drink offers a gentle energy boost and is packed with antioxidants, making it a healthy and delicious alternative to coffee.',
        'imageUrl': 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800',
        'cookTime': 5,
        'calories': 180,
        'rating': 4.6,
        'category': 'Drinks',
        'ingredients': ['Matcha powder', 'Hot water', 'Oat milk', 'Honey', 'Ice cubes'],
        'steps': ['Whisk matcha with hot water', 'Sweeten with honey', 'Pour over ice and milk', 'Stir well'],
        'authorId': 'chef_team',
        'authorName': 'Barista Bob',
        'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
      },
      {
        'title': 'Strawberry Lemonade',
        'description': 'Sweet and tangy homemade lemonade with fresh strawberries. The perfect summer refresher that combines the classic zing of lemonade with the sweet, fruity notes of ripe strawberries.',
        'imageUrl': 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9d?w=800',
        'cookTime': 10,
        'calories': 150,
        'rating': 4.5,
        'category': 'Drinks',
        'ingredients': ['Fresh strawberries', 'Lemons', 'Sugar syrup', 'Sparkling water', 'Mint'],
        'steps': ['Muddle strawberries', 'Squeeze lemons', 'Mix with syrup and water', 'Garnish with mint'],
        'authorId': 'chef_team',
        'authorName': 'Summer Vibes',
        'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
      },
      {
        'title': 'Refreshing Mango Lassi',
        'description': 'Traditional Indian yogurt-based drink with sweet mango pulp. Smooth, creamy, and exotic, this beverage is a delightful way to cool down and enjoy the sweet essence of ripe mangoes.',
        'imageUrl': 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=800',
        'cookTime': 5,
        'calories': 260,
        'rating': 4.8,
        'category': 'Drinks',
        'ingredients': ['1 ripe mango', '1 cup yogurt', '1/2 cup milk', 'Honey', 'Cardamom'],
        'steps': ['Peel and chop mango', 'Blend all ingredients until smooth', 'Serve chilled'],
        'authorId': 'chef_team',
        'authorName': 'Barista Bob',
        'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
      },
      {
        'title': 'Lemon Mint Cooler',
        'description': 'Zesty lemon juice with fresh mint and crushed ice. A sharp and revitalizing drink that clears the palate and provides an instant burst of citrusy freshness on a hot afternoon.',
        'imageUrl': 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800',
        'cookTime': 5,
        'calories': 120,
        'rating': 4.6,
        'category': 'Drinks',
        'ingredients': ['2 lemons', 'Fresh mint leaves', 'Sparkling water', 'Sugar', 'Ice'],
        'steps': ['Squeeze lemon juice', 'Muddle mint with sugar', 'Add ice and water', 'Stir and enjoy'],
        'authorId': 'chef_team',
        'authorName': 'Summer Vibes',
        'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
      },
      {
        'title': 'Extra Rich Hot Chocolate',
        'description': 'Creamy chocolate drink topped with marshmallows and cocoa powder. The ultimate winter indulgence, featuring high-quality dark chocolate melted into warm milk for a velvety smooth experience.',
        'imageUrl': 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800',
        'cookTime': 10,
        'calories': 380,
        'rating': 4.9,
        'category': 'Drinks',
        'ingredients': ['2 cups milk', '1/4 cup cocoa powder', 'Sugar', 'Dark chocolate chips', 'Marshmallows'],
        'steps': ['Warm milk in a pot', 'Whisk in cocoa and sugar', 'Add chocolate chips until melted', 'Top with marshmallows'],
        'authorId': 'chef_team',
        'authorName': 'Barista Bob',
        'createdAt': DateTime.now().subtract(const Duration(days: 3)).toIso8601String(),
      },
      {
        'title': 'Iced Peach Tea',
        'description': 'Homemade black tea infused with sweet peach flavors. A sophisticated and light beverage that captures the essence of summer orchards in every refreshing sip.',
        'imageUrl': 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800',
        'cookTime': 15,
        'calories': 140,
        'rating': 4.5,
        'category': 'Drinks',
        'ingredients': ['2 black tea bags', '1 peach', 'Sugar syrup', 'Ice', 'Water'],
        'steps': ['Brew tea and let cool', 'Slice peach and muddle some in glass', 'Add tea, syrup, and ice', 'Garnish with peach slices'],
        'authorId': 'chef_team',
        'authorName': 'Summer Vibes',
        'createdAt': DateTime.now().subtract(const Duration(days: 4)).toIso8601String(),
      },
      {
        'title': 'Green Machine Smoothie',
        'description': 'Healthy blend of spinach, apple, ginger, and cucumber. Kickstart your health with this nutrient-packed green smoothie that doesn\'t compromise on taste while giving you a natural energy boost.',
        'imageUrl': 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=800',
        'cookTime': 5,
        'calories': 190,
        'rating': 4.4,
        'category': 'Drinks',
        'ingredients': ['Handful spinach', '1 green apple', 'Cucumber', 'Small piece ginger', 'Apple juice'],
        'steps': ['Chop apple and cucumber', 'Add all ingredients to blender', 'Blend until very smooth'],
        'authorId': 'chef_team',
        'authorName': 'Smoothie King',
        'createdAt': DateTime.now().subtract(const Duration(days: 5)).toIso8601String(),
      },
      {
        'title': 'Signature Virgin Mojito',
        'description': 'Refreshing mix of lime, mint leaves, and sparkling lemonade. This mocktail is a crowd-pleaser, offering a crisp and sophisticated flavor profile that\'s perfect for any festive occasion or relaxed evening.',
        'imageUrl': 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800',
        'cookTime': 10,
        'calories': 160,
        'rating': 4.7,
        'category': 'Drinks',
        'ingredients': ['1 lime', 'Mint leaves', 'Simple syrup', 'Club soda', 'Ice'],
        'steps': ['Muddle lime and mint', 'Add syrup and ice', 'Fill with club soda', 'Stir gently'],
        'authorId': 'chef_team',
        'authorName': 'Barista Bob',
        'createdAt': DateTime.now().subtract(const Duration(days: 6)).toIso8601String(),
      },
    ];

    final auth = FirebaseAuth.instance;
    final user = auth.currentUser;
    final String uid = user?.uid ?? 'guest_user';
    final String username = user?.displayName ?? 'Guest Chef';

    
    for (var recipeData in sampleRecipes) {
      recipeData['authorId'] = uid;
      recipeData['authorName'] = username;

      final existing = await _firestore
          .collection('recipes')
          .where('title', isEqualTo: recipeData['title'])
          .limit(1)
          .get();

      if (existing.docs.isEmpty) {
        await _firestore.collection('recipes').add(recipeData);
      } else {
        final docId = existing.docs.first.id;
        await _firestore.collection('recipes').doc(docId).update({
          'imageUrl': recipeData['imageUrl'],
          'description': recipeData['description'],
          'calories': recipeData['calories'] ?? 0,
          'cookTime': recipeData['cookTime'],
          'rating': recipeData['rating'],
          'ingredients': recipeData['ingredients'],
          'steps': recipeData['steps'],
          'category': recipeData['category'],
        });
      }
    }
  }
}


